0.22217039464708083

array([ 1.28213868, -1.39644058])

In [1]:
%matplotlib inline
from GitHub.BayesML.bayesml import linearregression
import os
import numpy as np
import sys
NUM_PARAMS = 20
NUM_SAMPLE = 20
SAMPLE_SIZE = 100
STEP = 20
def zero_one_loss(y,y_hat):
    if y == y_hat:
        return 0
    else:
        return 1

def squared_loss(y,y_hat):
    return (y-y_hat)**2


for i in range(NUM_PARAMS):
    for j in range(NUM_SAMPLE):
        os.makedirs(f"./data/{i:02}/{j:02}")
model = linearregression.GenModel()
model.save_h_params("./data/hparams")
for i in range(NUM_PARAMS):
    model.gen_params()
    model.save_params(f"./data/{i:02}/params") 
    for j in range(NUM_SAMPLE):
        model.gen_sample(SAMPLE_SIZE)
        model.save_sample(f"./data/{i:02}/{j:02}/sample")
        
# ベイズリスク確認
loss_proposal = np.zeros([NUM_PARAMS,NUM_SAMPLE,SAMPLE_SIZE//STEP])
loss_comparison = np.zeros([NUM_PARAMS,NUM_SAMPLE,SAMPLE_SIZE//STEP])
model =  linearregression.LearnModel()
for i in range(NUM_PARAMS):
    true_param = np.load(f"./data/{i:02}/params.npz")["w"]

    for j in range(NUM_SAMPLE):
        sample_X = np.load(f"./data/{i:02}/{j:02}/sample.npz")["X"]
        sample_t=  np.load(f"./data/{i:02}/{j:02}/sample.npz")["t"]

        for  k in range(SAMPLE_SIZE//STEP):
            model.reset_hn_params()
            model.update_posterior(sample_X[:(k+1)*STEP],sample_t[:(k+1)*STEP])
            w,beta = model.estimate_params(loss="squared")
            print(beta)
            print(w)
            loss_proposal[i,j,k] = squared_loss(true_param, w)
            
        np.save(f"./data/{i:02}/{j:02}/loss_proposal",loss_proposal[i,j])
        np.save(f"./data/{i:02}/{j:02}/loss_comparison",loss_comparison[i,j])

    np.save(f"./data/{i:02}/risk_proposal",loss_proposal[i].sum(axis=0)/NUM_SAMPLE)
    np.save(f"./data/{i:02}/risk_comparison",loss_comparison[i].sum(axis=0)/NUM_SAMPLE)

np.save("./data/bayes_risk_proposal",loss_proposal.sum(axis=(0,1))/NUM_PARAMS/NUM_SAMPLE)
np.save("./data/bayes_risk_comparison",loss_comparison.sum(axis=(0,1))/NUM_PARAMS/NUM_SAMPLE)

print(loss_proposal.sum(axis=(0,1))/NUM_PARAMS/NUM_SAMPLE)

[[40.67456526]]
[1.71718801]
[[66.21520001]]
[1.80303066]
[[150.2515351]]
[1.85822068]
[[193.29313905]]
[1.88317877]
[[244.86798052]]
[1.90730856]
[[14.18435374]]
[1.83247659]
[[56.33114115]]
[1.86933465]
[[144.42435261]]
[1.92751037]
[[162.81878446]]
[1.93515982]
[[219.03417024]]
[1.95064359]
[[75.0206223]]
[1.95144594]
[[77.3601189]]
[1.95140061]
[[172.81972785]]
[1.95290309]
[[222.25422282]]
[1.96999024]
[[307.62708508]]
[1.94699567]
[[41.36013754]]
[1.92001635]
[[105.17021894]]
[1.87617703]
[[117.35190674]]
[1.91835567]
[[145.04012901]]
[1.92112506]
[[211.05957999]]
[1.92267813]
[[27.95310131]]
[1.85178094]
[[73.12990769]]
[1.83827902]
[[146.3102315]]
[1.87769859]
[[163.80083372]]
[1.92194894]
[[258.6584824]]
[1.92567906]
[[30.75016431]]
[1.86260453]
[[78.4531845]]
[1.92303911]
[[136.1840156]]
[1.92731263]
[[199.84680502]]
[1.94119462]
[[275.3698969]]
[1.94799188]
[[38.04874905]]
[1.82272738]
[[42.72700476]]
[1.89667754]
[[127.8364543]]
[1.93165577]
[[185.03781297]]
[1.93860267]
[[

[[46.1275962]]
[1.60136761]
[[181.42083892]]
[1.58189894]
[[645.01578387]]
[1.59508364]
[[847.65511373]]
[1.57112552]
[[1654.62561203]]
[1.57696193]
[[117.9103019]]
[1.63442602]
[[308.77484581]]
[1.74246865]
[[573.12795668]]
[1.73231442]
[[992.68284263]]
[1.73569419]
[[1759.20878495]]
[1.76791333]
[[67.23076646]]
[1.38532823]
[[234.25695902]]
[1.47282551]
[[669.27218524]]
[1.56109444]
[[1189.35211284]]
[1.56112031]
[[2010.9874125]]
[1.58635759]
[[185.00108879]]
[1.68332618]
[[242.43145906]]
[1.52357923]
[[917.06181966]]
[1.50117934]
[[1570.00825171]]
[1.59683994]
[[1920.80456213]]
[1.58347831]
[[175.21482182]]
[1.55143272]
[[248.80749947]]
[1.69103108]
[[815.37993797]]
[1.63566385]
[[1366.1508453]]
[1.58811627]
[[1495.41866664]]
[1.64897901]
[[89.57733175]]
[1.47313774]
[[311.66409329]]
[1.57473511]
[[616.5279118]]
[1.60943306]
[[929.70143633]]
[1.64339072]
[[1468.28820768]]
[1.6613058]
[[104.19768389]]
[1.86715145]
[[331.35433683]]
[1.64031959]
[[608.95569858]]
[1.67601926]
[[1235.061

[[4936.84324885]]
[-0.9015699]
[[709.35017782]]
[-0.64119829]
[[841.14760765]]
[-0.70227176]
[[2288.96313435]]
[-0.63590803]
[[3958.10367232]]
[-0.63435551]
[[6800.37582418]]
[-0.65178702]
[[43.22472615]]
[-2.39623232]
[[111.02930683]]
[-2.48728989]
[[142.01711338]]
[-2.50310139]
[[217.61384116]]
[-2.4984417]
[[327.92573554]]
[-2.50891007]
[[27.78417876]]
[-2.44305674]
[[81.18308601]]
[-2.4187342]
[[131.47697024]]
[-2.49077096]
[[177.60827403]]
[-2.46540086]
[[292.34247011]]
[-2.49320403]
[[78.49342892]]
[-2.45204985]
[[62.46814843]]
[-2.45731737]
[[129.84470683]]
[-2.47866283]
[[255.81908685]]
[-2.47897408]
[[237.8831151]]
[-2.49169104]
[[28.91283398]]
[-2.40612741]
[[76.35255947]]
[-2.43086426]
[[150.37239283]]
[-2.43758809]
[[193.77020996]]
[-2.47889372]
[[238.39858936]]
[-2.47825056]
[[29.15153787]]
[-2.49982542]
[[84.79005558]]
[-2.49191341]
[[191.46228224]]
[-2.5347907]
[[221.23959133]]
[-2.50519809]
[[318.85811219]]
[-2.50689345]
[[50.58932976]]
[-2.3832003]
[[80.68850977]]
[-2.

[[474.7443647]]
[0.39825467]
[[1869.04346781]]
[1.15525095]
[[5709.41273837]]
[0.81243829]
[[9866.65979776]]
[0.50022923]
[[13415.774513]]
[0.32230558]
[[1176.14088233]]
[0.67411051]
[[2677.36146308]]
[0.36610529]
[[5450.51856824]]
[0.26537406]
[[13773.6649402]]
[0.19872865]
[[20019.63912541]]
[0.26343553]
[[629.94982103]]
[0.68737774]
[[2360.79661663]]
[0.90274755]
[[4980.70359907]]
[0.74342818]
[[13701.35258645]]
[0.72872223]
[[21517.80157528]]
[0.65573286]
[[1033.06046674]]
[1.20566504]
[[3254.29139109]]
[0.46104064]
[[7334.99201752]]
[0.60819963]
[[13062.07350644]]
[0.6827862]
[[14201.61019877]]
[0.56074112]
[[668.31899169]]
[0.82933537]
[[2904.94411015]]
[0.7876236]
[[5383.22018758]]
[0.55610707]
[[13268.65058244]]
[0.66512111]
[[19294.73227373]]
[0.36713156]
[[74.26155874]]
[1.07787745]
[[228.91292494]]
[1.23647679]
[[334.6684205]]
[1.20635879]
[[831.04825575]]
[1.12830809]
[[931.29940664]]
[1.12595548]
[[40.97888044]]
[0.92905911]
[[118.94995991]]
[1.01392072]
[[238.36619011]]
[

[[275.02369148]]
[0.29597674]
[[10.35534008]]
[-0.74558884]
[[24.56023511]]
[-0.61562961]
[[31.7113937]]
[-0.65988131]
[[49.71611053]]
[-0.68575964]
[[68.56276386]]
[-0.68684767]
[[12.77246801]]
[-0.81241184]
[[19.53873492]]
[-0.65672671]
[[37.10215652]]
[-0.66402004]
[[68.69806836]]
[-0.66090012]
[[65.63666738]]
[-0.6838671]
[[15.42099496]]
[-0.65890342]
[[29.23787296]]
[-0.69875468]
[[54.94258868]]
[-0.69909049]
[[54.20225924]]
[-0.69088659]
[[62.43721774]]
[-0.70659086]
[[10.92508623]]
[-0.59592879]
[[29.59511802]]
[-0.66647118]
[[47.29049986]]
[-0.66764536]
[[59.08429142]]
[-0.68730692]
[[81.97023772]]
[-0.70547044]
[[11.12257332]]
[-0.68730349]
[[26.66881977]]
[-0.72160931]
[[32.03369545]]
[-0.72971651]
[[56.84677929]]
[-0.68952826]
[[78.60748839]]
[-0.71442246]
[[6.12940271]]
[-0.67355259]
[[27.23532395]]
[-0.70593757]
[[47.46503711]]
[-0.66625793]
[[70.40267007]]
[-0.70462442]
[[78.87801263]]
[-0.66399782]
[[17.23131946]]
[-0.73906236]
[[24.15324688]]
[-0.65542557]
[[45.44800602

[[108.16665597]]
[1.86332021]
[[130.43658666]]
[1.87348616]
[[13.20086457]]
[-0.66222339]
[[28.35794604]]
[-0.61727069]
[[66.21652497]]
[-0.61870118]
[[66.03715558]]
[-0.66795903]
[[80.58213445]]
[-0.67347921]
[[16.30816409]]
[-0.61439983]
[[30.58130277]]
[-0.70693634]
[[59.8004444]]
[-0.68733828]
[[62.5150981]]
[-0.64690982]
[[94.05554676]]
[-0.67861441]
[[19.04663037]]
[-0.62130952]
[[34.55518393]]
[-0.6367395]
[[48.35236637]]
[-0.678385]
[[72.97444226]]
[-0.68582391]
[[94.06218457]]
[-0.66112856]
[[17.38732546]]
[-0.74485701]
[[21.75727408]]
[-0.66358549]
[[59.42014691]]
[-0.64161092]
[[65.20935502]]
[-0.66669069]
[[87.313635]]
[-0.68238578]
[[7.20218529]]
[-0.63804392]
[[37.03178055]]
[-0.65435577]
[[49.00097749]]
[-0.63629406]
[[66.12107067]]
[-0.64489145]
[[96.39220159]]
[-0.65676782]
[[16.29419491]]
[-0.46366578]
[[29.1113752]]
[-0.59293208]
[[43.01672006]]
[-0.68239133]
[[54.02297298]]
[-0.67101764]
[[102.76221729]]
[-0.63874798]
[[11.833223]]
[-0.61143089]
[[28.56154604]]
[-0.

[[177.02504367]]
[-1.72301616]
[[738.77166146]]
[-1.90837778]
[[893.29045517]]
[-1.88859143]
[[1522.44600382]]
[-1.98260955]
[[3103.08205838]]
[-1.99680816]
[[86.37252394]]
[-1.68937001]
[[371.97536157]]
[-1.72920775]
[[803.81485749]]
[-1.79009722]
[[1586.53531319]]
[-1.82889628]
[[2622.08087448]]
[-1.86061482]
[[74.72966735]]
[-2.07170059]
[[336.82295416]]
[-2.1092171]
[[853.27679878]]
[-2.17530658]
[[1389.98325838]]
[-2.16542767]
[[2882.36342611]]
[-2.16814291]
[[113.14814776]]
[-2.14591907]
[[340.61088583]]
[-1.97278871]
[[659.11589945]]
[-1.96473832]
[[1814.50410717]]
[-1.99912991]
[[2727.03743103]]
[-2.04677133]
[[293.16529628]]
[-1.84498778]
[[854.87884897]]
[-1.91174216]
[[1587.7317895]]
[-1.85166514]
[[1463.98923857]]
[-1.91448973]
[[2997.93383548]]
[-1.99998517]
[[73.82101497]]
[-1.76892786]
[[363.96262323]]
[-2.00217288]
[[754.31234419]]
[-2.04139174]
[[1396.88621243]]
[-2.052405]
[[2234.95866388]]
[-2.09782748]
[[79.42007825]]
[-2.02484499]
[[372.11603146]]
[-2.1354285]
[[86

In [10]:
data=np.load(f"./data/00/params.npz")["w"]
print(data)

[0.38610741]


In [25]:
a=[[5]]
a=np.array(a)
np.linalg.inv(a)


array([[0.2]])

In [26]:
beta = np.random.gamma(shape=1, scale=1,size=1)
beta

array([0.06521197])

In [33]:
p

array([4.45655986, 1.86482294])

In [29]:
t[1]*X[1]

array([-0.29353866, -1.85596977])

In [30]:
X[1]

array([-0.21694314, -1.37167593])

In [31]:
t[1]

1.3530672421563261